config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :visitor
  root 'visitor#index'
  resources :gaming
  resources :newspaper
  resources :business
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord 
  validates :email, presence:true
  validates :name, presence:true
  validates :phone_number, presence:true
  validates_uniqueness_of :email
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/gaming.rb
class Gaming < ApplicationRecord
end

app/models/newspaper.rb
class Newspaper < ApplicationRecord
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  validates :email, presence:true
  validates_uniqueness_of :email
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/business_controller.rb
class BusinessController < ApplicationController
  def index
    @business = Business.new
  end

  def new
    @business = Business.new
  end
  
  def create
    @business = Business.new(business_params)
      if @business.save
      flash[:success] = "Nous avons reçu vos coordonnées, nous vous contacterons au plus vite"
      MainMailer.business_email(@business).deliver_now
      else
      flash[:danger] = "Adresse email manquante"

      end
   redirect_to business_index_path
  end

  def business_params
    params.require(:business).permit(:name,:phone_number,:email)
  end
end

app/controllers/gaming_controller.rb
class GamingController < ApplicationController
  def index
    @gaming = Gaming.new
  end

  def new
    @gaming = Gaming.new
  end
  
  def create
    @gaming = Gaming.new(email: visitor_params[:email])
   if @gaming.save
    flash[:success] = "Message Bien Envoyé !"
    MainMailer.gaming_email(@gaming).deliver_now
   else
    flash[:danger] = "Message non remis : Adresse email manquante"
   end
   redirect_to gaming_index_path
  end

  def visitor_params
    params.require(:gaming).permit(:email)
  end

end

app/controllers/newspaper_controller.rb
class NewspaperController < ApplicationController
  def index
    @newspaper = Newspaper.new
  end

  def new
    @newspaper = Newspaper.new
  end
  
  def create
    @newspaper = Newspaper.new(email: visitor_params[:email])
   if @newspaper.save
    flash[:success] = "Message Bien Envoyé !"
    MainMailer.newspaper_email(@newspaper).deliver_now
   else
    flash[:danger] = "Message non remis : Adresse email manquante"
   end
   redirect_to newspaper_index_path
  end

  def visitor_params
    params.require(:newspaper).permit(:email)
  end

end

app/controllers/showcase_controller.rb
class ShowcaseController < ApplicationController
    def index
      @slideshow_images_names = ['dog1', 'dog2', 'dog3']
      @slideshow_selected_image_index = 1
    end
end

app/controllers/visitor_controller.rb
class VisitorController < ApplicationController
  def index
    @visitor = Visitor.new
    
  end

  def new
    @visitor = Visitor.new
  end
  
  def create
    @visitor = Visitor.new(first_name: visitor_params[:first_name], last_name: visitor_params[:last_name], phone_number: visitor_params[:phone_number], email: visitor_params[:email], message: visitor_params[:message])
    a = is_known
      if @visitor.email.nil? 
      flash[:danger] = "Adresse email manquante"
      elsif a == 1
      flash[:danger] = "Adresse email déjà enregistrée"
      elsif @visitor.save
      flash[:success] = "Adresse e-mail enregistrée, vous recevrez l'actualité de Shomi prochainement"
      else
        flash[:danger] = "Adresse email invalide ou déjà enregistrée"
      end
   redirect_to root_path
  end

  def visitor_params
    params.require(:visitor).permit(:first_name,:last_name,:phone_number,:email,:message)
  end

  def is_known
    a = 0
    Visitor.all.each {|visitor| visitor.email == @visitor.email ? a = 1 : a = 0 }
    return a
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/gaming_helper.rb
module GamingHelper
end

app/helpers/newspaper_helper.rb
module NewspaperHelper
end

app/helpers/showcase_helper.rb
module ShowcaseHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/views/business/_boutique.html.erb
<a name = "boutique">
<div class="prodetail">
  <div class="protitle">
  <h2>Notre proposition </h2><hr class="underline1"><strong><span class="subtitle">Avec Shomi : </br></br>-Votre audience ne subit plus la pub, elle choisit quand elle la regarde</br></br> -Votre audience est rémunérée pour son engagement</br></strong>
    <div class="prosecondtitle">
    <h2>Une solution modulable pour votre entreprise<h2><hr class="underline2"><span class="subtitle">Grâce à notre hyper-targeting et à nos profils détaillés d'utilisateurs :</span>
    </div></div>
    <div class="cardsdisplay">
    <div class="card1">
    <div class="iconwrap"><i class="fas fa-bullseye" id="icontarget"></i></div></br>
    <div class="cardtext">
    Générez de l'engagement et des leads qualifiés</div>
    </div>
    <div class="card1">
    <div class="iconwrap"><i class="fas fa-comment-dots"></i></div></br>
    <div class="cardtext">
    Profitez d'un feedback utilisateur détaillé</div>
    </div>
    <div class="card1">
    <div class="iconwrap"><i class="fas fa-vial"></i></div></br>
    <div class="cardtext">
    Testez vos campagnes avant de les lancer</div>
    </div>
    </div>

</div>





</div>
</a>

app/views/business/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue-grey lighten-5">

  <div style="background-color: #21d192;">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0">Retrouvez-nous sur les Réseaux Sociaux !</h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f white-text mr-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter white-text mr-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g white-text mr-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in white-text mr-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram white-text"> </i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>
 
  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3 dark-grey-text">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

        <!-- Content -->
        <img class="img-responsive" width="100px" height="" src="<%= asset_path( 'logo.svg' ) %>"></br></br>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <span class="justifyparag"><p>Shomi est une plate-forme qui permet à ses utilisateurs d'avoir accès à des services en effectuant des actions quotidiennes.</p></span>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->


      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Coordonnées</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
        <p>
        7 parvis Alan Turing, 75013 Paris</br></br>
           contact@shomi.xyz</p>
    

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->


</footer>
<!-- Footer -->

app/views/business/_form.html.erb
<div class="formwrap">
  <div class="container" id="formpro">
    <div class="formcontainer">
      </br> <h2>Contact</h2></br>
      <div class="info-form">
        <%= form_for @business, url: business_index_path, html: {action: :post, class: "form-signin mt-3" } do |f| %>
          <div class="form-group">
            <%= f.text_field :name, autocomplete: "name", placeholder: "Nom de l'entreprise", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.text_field :phone_number, autocomplete: "phone_number", placeholder: "Numéro de téléphone", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.text_field :email, autocomplete: "email", placeholder: "Adresse email", class: "form-control" %>
          </div>
          <div class="actions mt-5">
            <%= submit_tag "Valider", :class => 'btn btn-info btn-lg btn-block btn-red'  %>
          </div>
          <% end %>
        </div>
      </div> 
  </div>
</div>

app/views/business/_jumbotron.html.erb
<div class="jumbotron jumbpro py-2">
  <section id="cover">
    <div class="row prowrap">
      <div class="container column titlepro" id="titlepro"><h1>La publicité digitale capte seulement 20 % de l'attention de votre audience !</h1><hr class="title"></br><span class="subtitlepro"><strong>Shomi : Une délivrance pour votre audience trop souvent victime de campagnes agressives</strong></span>
      </div>
      <div class="imagewrap">
    <img class="img-responsive screenapp" src="<%= asset_path( 'appscreen.png' ) %>">
    </div>     
      </div>
    </section>
  </p>
</div>

app/views/business/_navbar.html.erb
<nav class="navbar navbar-expand-md navbarland" id="navbarlanding"> 
  <div class="navlandmob">
      <img class="img-responsive logoland" src="<%= asset_path( 'logo.svg' ) %>">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">

      </button>
  </div>
      <div class="collapse navbar-collapse menuland" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item navmob">

          </li>
        </ul>
      </div>

</nav>  

app/views/business/_partners.html.erb
<div class="partners">
  <div class="partnerstitle">
  <strong>Nos partenaires</strong>
  </div>
  <div class="partnerscontent">
  <img class="img-responsive pepite" src="<%= asset_path( 'pepite.png' ) %>">
  <img class="img-responsive stationf" src="<%= asset_path( 'station_f.svg' ) %>">
  <img class="img-responsive schoolab" src="<%= asset_path( 'schoolab.png' ) %>">
  </div>
</div>

app/views/business/_popup.html.erb
<div class="popupwindow" id="popupwindow">
  <div class="headpopup">
  <button id="close" onclick="closePopup()">Fermer</button>
  </div>
  <div class="videopopup">
  <iframe id="video" class="videopop" src='https://www.youtube.com/embed/ACw8909qXtg?enablejsapi=1&html5=1rel=0&autoplay=1' frameborder='0' allowfullscreen allow="autoplay; encrypted-media"></iframe>
  </div>
</div>

app/views/business/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>Shomi | Hyper-ciblage</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  </head>

  <body>
<%= render 'navbar' %>
<%= render 'popup' %>
<%= render 'jumbotron' %>

<%= render 'visitor/flash' %>
<%= render 'boutique' %>

<%= render 'form' %>
<%= render 'partners' %>
<%= render 'footer' %>

<%= yield %>

<%= yield %>
<script scr="popup.js" type="text/javascript"></script>
</body>
</html>

app/views/gaming/_boutique.html.erb
<a name = "boutique">
<div class="shopwrap">
  <div class="shoptitle">
  <h2>La Boutique </h2></div>
  <div class="shopcontent">

    <div class="item" id="shoplogos">
      <img class="img-responsive" width="100px" height="" src="<%= asset_path( 'vbucks.svg' ) %>"></br></br></br><h3> 1 000 V-Bucks = 50 Shomi's </h3>
    </div>

    <div class="item" id="shoplogos">
      <img class="img-responsive" width="100px" height="" src="<%= asset_path( 'riotpoint.svg' ) %>"></br></br></br><h3> 1 380 Riot Points = 50 Shomi's</h3>
    </div>

    <div class="item" id="shoplogos">
    <img class="img-responsive" width="100px%" height="" src="<%= asset_path( 'coin.svg' ) %>"></br></br></br> <h3>10 € = 50 Shomi's</h3>
    </div>

  </div>


</div>
</a>

app/views/gaming/_jumbotron2.html.erb
<div class="jumbotron jumboindex py-2">
<div class="logowrap">
  <img class="img-responsive" width="150px" height="" src="<%= asset_path( 'logo.svg' ) %>">
</div>
<section id="cover">
<div class="row">
<div class="container column" id="firsttitle"><h1><span class="titlejumb">Marre de Payer vos Premiums ? </br>Inscrivez-vous !</span></br></br></div></h1>
<div class="container column" id="titlepage">
<h1>V-Bucks <span class="jumboemphaz">Gratuit.</span></br>Riot Points <span class="jumboemphaz">Gratuit.</span></br>PSN <span class="jumboemphaz">Gratuit.</span></h1></div>
    <div class="container column" id="form1">
    <div class="formcontainer">
    <div class="titleform">
          </div>
          </br> Entrez votre adresse mail pour obtenir toutes les informations concernant Shomi
          <div class="info-form">
              <%= form_for @gaming, url: gaming_index_path, html: {action: :post, class: "form-signin mt-3" } do |f| %>
                  <div class="form-group">
                  <%= f.text_field :email, autocomplete: "email", placeholder: "Adresse email", class: "form-control" %>
                  </div>
                  <div class="actions mt-5">
                  <%= submit_tag "Valider", :class => 'btn btn-info btn-lg btn-block'  %>
                </div>
              <% end %>
        </div>
        </div>
            
  </div>
</section>
</p>
</div>

app/views/gaming/_menu.html.erb
<div class="processus firstline" id="firstlinemenu">


      <div class="mdl-stepper-step active-step" id="step1"><%= link_to gaming_index_path(anchor: "shomis") do %>
        <div class="mdl-stepper-circle"><span>1</span></div>
        <div class="mdl-stepper-title">Vous regardez une vidéo</div>
        <div class="mdl-stepper-bar-left"></div>
        <div class="mdl-stepper-bar-right"></div><%end%>
      </div>
      <div class="mdl-stepper-step active-step" id="step1"><%= link_to gaming_index_path(anchor: "shomis") do %>
        <div class="mdl-stepper-circle"><span>2</span></div>
        <div class="mdl-stepper-title">Vous répondez aux questions</div>
        <div class="mdl-stepper-bar-left"></div>
        <div class="mdl-stepper-bar-right"></div><%end%>
      </div>
      <div class="mdl-stepper-step active-step" id="step1"><%= link_to gaming_index_path(anchor: "shomis") do %>
        <div class="mdl-stepper-circle"><span>3</span></div>
        <div class="mdl-stepper-title">Vous recevez 1 Shomi</div>
        <div class="mdl-stepper-bar-left"></div></a><%end%>
      </div>
</div>

<div class="processus secondline" id="secondlinemenu">
      <div class="mdl-stepper-step active-step" id="step4"><%= link_to gaming_index_path(anchor: "boutique") do %>
        <div class="mdl-stepper-circle"><span>4</span></div>
        <div class="mdl-stepper-title">Boutique Shomis</div>
        <div class="mdl-stepper-bar-right"></div></a><%end%>
      </div>
</div>




  
  
  
  
  

app/views/gaming/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shomi | V-Bucks et PSN Gratuit |</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  </head>

<body>

<%= render 'jumbotron2' %>
<%= render 'visitor/flash' %>
<%= render 'menu' %>
<%= render 'boutique' %>
<%= render 'visitor/video' %>
<%= render 'visitor/questions' %>
<%= render 'visitor/earn' %>
<%= render 'visitor/footer' %>
<%= yield %>

</body>
</html>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-151656422-1', 'shomi.xyz');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'logosmall.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= render 'layouts/ga' %>
    <script src="https://kit.fontawesome.com/8d177e7f8d.js" crossorigin="anonymous"></script>

    
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>

app/views/newspaper/_boutique.html.erb
<a name = "boutique">
<div class="shopwrap">
  <div class="shoptitle">
  <h2>La Boutique </h2></div>
  <div class="shopcontent">

    <div class="item" id="shoplogos">
      <img class="img-responsive" width="180px" height="" src="<%= asset_path( 'lemonde.svg' ) %>"></br></br></br><h3> 1 Mois = 50 Shomi's </h3>
    </div>

    <div class="item" id="shoplogos">
      <img class="img-responsive" width="100px" height="" src="<%= asset_path( 'figaro.svg' ) %>"></br></br></br><h3> 1 Mois = 50 Shomi's</h3>
    </div>

    <div class="item" id="shoplogos">
    <img class="img-responsive" width="100px%" height="" src="<%= asset_path( 'parisien.svg' ) %>"></br></br></br> <h3>1 Mois = 50 Shomi's</h3>
    </div>

  </div>


</div>
</a>

app/views/newspaper/_jumbotron3.html.erb
<div class="jumbotron jumboindex py-2">
<div class="logowrap">
  <img class="img-responsive" width="150px" height="" src="<%= asset_path( 'logo.svg' ) %>">
</div>
<section id="cover">
<div class="row">
<div class="container column" id="firsttitle"><h1><span class="titlejumb">Marre de Payer vos Journaux ? </br>Inscrivez-vous !</span></br></br></div></h1>
<div class="container column" id="titlepage">
<h1>Le Monde <span class="jumboemphaz">Gratuit.</span></br>Le Figaro <span class="jumboemphaz">Gratuit.</span></br>Le Parisien <span class="jumboemphaz">Gratuit.</span></h1></div>
    <div class="container column" id="form1">
    <div class="formcontainer">
    <div class="titleform">
          </div>
          </br> Entrez votre adresse mail pour obtenir toutes les informations concernant Shomi
          <div class="info-form">
              <%= form_for @newspaper, url: newspaper_index_path, html: {action: :post, class: "form-signin mt-3" } do |f| %>
                  <div class="form-group">
                  <%= f.text_field :email, autocomplete: "email", placeholder: "Adresse email", class: "form-control" %>
                  </div>
                  <div class="actions mt-5">
                  <%= submit_tag "Valider", :class => 'btn btn-info btn-lg btn-block'  %>
                </div>
              <% end %>
        </div>
        </div>
            
  </div>
</section>
</p>
</div>

app/views/newspaper/_menu.html.erb
<div class="processus firstline" id="firstlinemenu">


      <div class="mdl-stepper-step active-step" id="step1"><%= link_to newspaper_index_path(anchor: "shomis") do %>
        <div class="mdl-stepper-circle"><span>1</span></div>
        <div class="mdl-stepper-title">Vous Regardez une Vidéo</div>
        <div class="mdl-stepper-bar-left"></div>
        <div class="mdl-stepper-bar-right"></div><%end%>
      </div>
      <div class="mdl-stepper-step active-step" id="step1"><%= link_to newspaper_index_path(anchor: "shomis") do %>
        <div class="mdl-stepper-circle"><span>2</span></div>
        <div class="mdl-stepper-title">Vous Répondez aux Questions</div>
        <div class="mdl-stepper-bar-left"></div>
        <div class="mdl-stepper-bar-right"></div><%end%>
      </div>
      <div class="mdl-stepper-step active-step" id="step1"><%= link_to newspaper_index_path(anchor: "shomis") do %>
        <div class="mdl-stepper-circle"><span>3</span></div>
        <div class="mdl-stepper-title">Vous Recevez 1 Shomi's</div>
        <div class="mdl-stepper-bar-left"></div></a><%end%>
      </div>
</div>

<div class="processus secondline" id="secondlinemenu">
      <div class="mdl-stepper-step active-step" id="step4"><%= link_to newspaper_index_path(anchor: "boutique") do %>
        <div class="mdl-stepper-circle"><span>4</span></div>
        <div class="mdl-stepper-title">Boutique Shomi's</div>
        <div class="mdl-stepper-bar-right"></div></a><%end%>
      </div>
</div>




  
  
  
  
  

app/views/newspaper/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>Shomi | Abonnements Journaux Gratuit</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  </head>

  <body>

<%= render 'jumbotron3' %>
<%= render 'visitor/flash' %>
<%= render 'menu' %>
<%= render 'boutique' %>
<%= render 'visitor/video' %>
<%= render 'visitor/questions' %>
<%= render 'visitor/earn' %>
<%= render 'visitor/footer' %>
<%= yield %>

</body>
</html>

app/views/visitor/_boutique.html.erb
<a name = "boutique">
<div class="shopwrap">
  <div class="shoptitle">
  <h2>La Boutique </h2></div>
  <div class="shopcontent">

    <div class="item" id="shoplogos">
      <img class="img-responsive" width="100px" height="" src="<%= asset_path( 'netflix.svg' ) %>"></br></br></br><h3> 1 Mois = 40 Shomis </h3>
    </div>

    <div class="item" id="shoplogos">
      <img class="img-responsive" width="100px" height="" src="<%= asset_path( 'spotify.svg' ) %>"></br></br></br><h3> 1 Mois = 40 Shomis</h3>
    </div>

    <div class="item" id="shoplogos">
    <img class="img-responsive" width="100px%" height="" src="<%= asset_path( 'coin.svg' ) %>"></br></br></br> <h3>10 € = 40 Shomis</h3>
    </div>

  </div>


</div>
</a>

app/views/visitor/_form.html.erb
<section id="cover">
    <div id="cover-caption">
        <div id="container1" class="container">
                    <h1 class="display-10">DEMANDE DE CONTACT</h1>
                    <div class="info-form">
                        <%= form_for @visitor, url: visitor_index_path, html: {action: :post, class: "form-signin mt-3" } do |f| %>
                            <div class="form-group">
                            <%= f.text_field :email, autocomplete: "email", placeholder: "Adresse email", class: "form-control" %>
                            </div>
                            <div class="actions mt-5">
                            <%= submit_tag "Valider", :class => 'w-100 btn btn-primary'  %>
                          </div>
                       <% end %>
            </div>
        </div>
    </div>
</section>

app/views/visitor/_intersect.html.erb
<div class="intersect">

</div>

app/views/visitor/_jumbotron1.html.erb
<div class="jumbotron jumboindex py-2">
    <div class="logowrap">
      <img class="img-responsive" width="150px" height="" src="<%= asset_path( 'logo.svg' ) %>">
    </div>
    <section id="cover">
    <div class="row">
    <div class="container column" id="firsttitle"><h1><span class="titlejumb">Marre de payer vos abonnements ? </br>Inscrivez-vous !</span></br></br></div></h1>
    <div class="container column" id="titlepage">
    <h1>Netflix <span class="jumboemphaz">Gratuit.</span></br>Spotify <span class="jumboemphaz">Gratuit.</span></br>PSN <span class="jumboemphaz">Gratuit.</span></h1></div>
        <div class="container" id="form1">
        <div class="formcontainer">
        <div class="titleform">
              </div>
              </br> Entrez votre adresse mail pour obtenir toutes les informations concernant Shomi
              <div class="info-form">
                  <%= form_for @visitor, url: visitor_index_path, html: {action: :post, class: "form-signin mt-3" } do |f| %>
                      <div class="form-group">
                      <%= f.text_field :email, autocomplete: "email", placeholder: "Adresse email", class: "form-control" %>
                      </div>
                      <div class="actions mt-5">
                      <%= submit_tag "Valider", :class => 'btn btn-info btn-lg btn-block'  %>
                    </div>
                  <% end %>
            </div>
            </div>
                
      </div>
    </section>
  </p>
</div>